server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/blog_system?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    # druid
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

    #====================================== 模板配置 ===================================
  thymeleaf:
    cache: false




mybatis-plus:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.intellif.model1task4springboot.entity

#showSql
logging:
  level:
    com:
      intellif:
        model1task4springboot:
          dao : DEBUG




